<a href="https://colab.research.google.com/github/MazenMarei25/Machine-Learning-Practice-/blob/main/Regression/Robot_Inverse_Kin_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sandibaressiegota/robot-kinematics-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'robot-kinematics-dataset' dataset.
Path to dataset files: /kaggle/input/robot-kinematics-dataset


In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

data = pd.read_csv("/root/.cache/kagglehub/datasets/sandibaressiegota/robot-kinematics-dataset/versions/1/robot_inverse_kinematics_dataset.csv")

x = data.iloc[:,:-3].values
y = data.iloc[:,-3:].values



In [ ]:
print(data)

          q1     q2    q3     q4      q5     q6       x        y      z
0     -1.510 -0.763  1.85 -0.817  0.9120  2.320 -0.0947  0.15000  0.301
1     -2.840  0.520  1.58 -1.270 -1.3900  0.617  0.1420 -0.10000  0.225
2     -1.230  0.695  1.22 -1.130  0.0343  6.270 -0.0833  0.22300  0.206
3     -1.990  1.060  1.74 -1.760 -1.2400  4.760  0.1350 -0.03140  0.370
4      1.050  0.836  1.34 -1.890  0.4840  4.380 -0.0560 -0.22900  0.260
...      ...    ...   ...    ...     ...    ...     ...      ...    ...
14995  0.314 -0.534  1.76  1.970 -0.6990  3.870 -0.1130 -0.12800  0.257
14996  2.450  1.360  1.55  2.780 -0.3210  5.310  0.0633 -0.03160  0.450
14997  2.620  1.410  1.56  2.540  1.0600  5.870  0.1310 -0.16000  0.362
14998 -1.890  1.850  1.51  1.090  0.6970  4.070  0.0829 -0.01600  0.441
14999  2.680 -1.790  1.79  2.620  1.5900  2.640 -0.1570 -0.00369  0.254

[15000 rows x 9 columns]


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,      # 20% for testing, 80% for training
    random_state=42
)


In [ ]:
print(x_train)
print(y_train)

print(x_test)
print(y_test)

[[ 2.24e+00 -2.87e-01  1.57e+00  4.17e-01  1.33e+00  4.04e+00]
 [ 2.26e+00 -2.86e-01  1.51e+00  1.19e+00  7.15e-01  3.62e+00]
 [ 6.83e-01  1.25e+00  1.83e+00  3.30e-01  1.02e-01  6.35e-03]
 ...
 [ 1.16e+00 -1.70e+00  1.67e+00 -2.61e+00 -1.31e+00  1.79e+00]
 [-1.39e+00 -2.50e-03  1.74e+00  1.01e+00  8.84e-01  6.71e-01]
 [-2.81e+00 -9.61e-01  1.61e+00  1.04e+00  1.04e+00  5.40e+00]]
[[ 5.19e-03 -9.96e-02  3.29e-01]
 [ 6.12e-03 -1.48e-01  1.95e-01]
 [ 3.32e-04  6.55e-03  4.78e-01]
 ...
 [-9.70e-02 -4.34e-02  2.17e-01]
 [ 7.27e-02  1.37e-01  3.45e-01]
 [ 9.90e-02 -8.19e-02  2.08e-01]]
[[ 1.59e+00 -1.11e+00  1.47e+00  1.11e+00  5.72e-01  3.12e+00]
 [-3.34e-01 -1.25e+00  1.37e+00 -1.62e+00 -1.97e-03  5.03e+00]
 [ 1.09e+00  4.15e-01  1.31e+00 -5.13e-01 -3.47e-01  6.23e+00]
 ...
 [-1.57e+00 -1.09e+00  1.23e+00  1.05e+00  1.90e+00  6.34e-01]
 [ 4.44e-01  1.53e+00  1.50e+00  1.45e+00  1.01e+00  2.37e+00]
 [ 4.48e-01 -1.24e+00  1.61e+00  1.02e+00  8.66e-01  6.23e+00]]
[[-0.0714    0.000885  0.122

In [ ]:
print(x_train[0])

[ 2.24  -0.287  1.57   0.417  1.33   4.04 ]


In [ ]:
# standarize the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,:] = sc.fit_transform(x_train[:,:])
x_test[:,:] = sc.transform(x_test[:,:])



In [ ]:
print(x_train[0])

[ 1.35191756 -0.24532553 -0.01376603  0.25074057  1.10445076  0.49658945]


In [ ]:
#from sklearn.preprocessing import PolynomialFeatures
#from sklearn.linear_model import LinearRegression
#from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=300,max_depth=12,min_samples_leaf=6,min_samples_split=10,random_state=0)
#regressor = LinearRegression(
regressor.fit(x_train, y_train)

RandomForestRegressor(max_depth=12, min_samples_leaf=6, min_samples_split=10,
                      n_estimators=300, random_state=0)

In [ ]:
y_pred = regressor.predict(x_test)

In [ ]:
##Testing for overfitting by comparing R2 and Errors of trian and test predictions
y_train_pred = regressor.predict(x_train)

train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_pred)

train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_pred)

gap = train_r2 - test_r2



In [ ]:
#printf(train_r2)
#print(test_r2)
#print(train_mse)
#print(test_mse)
#print(gap)

print(f"train R2: {train_r2:.4f}")
print(f"test R2: {test_r2:.4f}")
print(f"train mse: {train_mse:.4f}")
print(f"test mse: {test_mse:.4f}")
print(f"R2 gap: {gap:.4f}")

train R2: 0.8549
test R2: 0.7794
train mse: 0.0016
test mse: 0.0025
R2 gap: 0.0755


In [ ]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

print("Performance Metrics:")
print("="*50)
for i, coord in enumerate(['X', 'Y', 'Z']):
    r2 = r2_score(y_test[:, i], y_pred[:, i])
    mse = mean_squared_error(y_test[:, i], y_pred[:, i])
    mae = mean_absolute_error(y_test[:, i], y_pred[:, i])
    print(f"{coord}-coordinate:")
    print(f"  R² Score: {r2:.4f}")
    print(f"  MSE: {mse:.4f}")
    print(f"  MAE: {mae:.4f}")
    print()

# Overall performance
overall_r2 = r2_score(y_test, y_pred)
overall_mse = mean_squared_error(y_test, y_pred)
print(f"Overall R² Score: {overall_r2:.4f}")
print(f"Overall MSE: {overall_mse:.4f}")

Performance Metrics:
X-coordinate:
  R² Score: 0.7335
  MSE: 0.0028
  MAE: 0.0430

Y-coordinate:
  R² Score: 0.7525
  MSE: 0.0028
  MAE: 0.0425

Z-coordinate:
  R² Score: 0.8521
  MSE: 0.0018
  MAE: 0.0335

Overall R² Score: 0.7794
Overall MSE: 0.0025


## **Comparision Between Linear Regression and Polynomial Regression Performance**


Performance Metrics Linear Regression:
==================================================
X-coordinate:
  R² Score: 0.0043
  MSE: 0.0106
  MAE: 0.0863

Y-coordinate:
  R² Score: 0.0632
  MSE: 0.0105
  MAE: 0.0847

Z-coordinate:
  R² Score: 0.4185
  MSE: 0.0072
  MAE: 0.0713

Overall R² Score: 0.1620
Overall MSE: 0.0094

Performance Metrics Polynomial (4th):
==================================================
X-coordinate:
  R² Score: 0.6294
  MSE: 0.0039
  MAE: 0.0497

Y-coordinate:
  R² Score: 0.6096
  MSE: 0.0044
  MAE: 0.0530

Z-coordinate:
  R² Score: 0.8829
  MSE: 0.0015
  MAE: 0.0291

Overall R² Score: 0.7073
Overall MSE: 0.0033

Commentray :
Comparing both linear and Poly.  R² Score we can see that overall Poly captures the regression better than linear alone
this is also reflected in the overall MSE were Poly provided a lower MSE



Performance Metrics (6th):
==================================================
X-coordinate:
  R² Score: 0.9299
  MSE: 0.0007
  MAE: 0.0194

Y-coordinate:
  R² Score: 0.8991
  MSE: 0.0011
  MAE: 0.0237

Z-coordinate:
  R² Score: 0.9900
  MSE: 0.0001
  MAE: 0.0081

Overall R² Score: 0.9397
Overall MSE: 0.0007

Commentary :

Polynomial degree of 8 provides an overall Overall R² Score: 0.9879
Overall MSE: 0.0001

